#!/usr/bin/env python3
"""
Build dist/SBMM_Site_Explorer.html — one self-contained file (CSS, JS, vendor libs,
and every data payload inlined). Double-click works anywhere, no folder needed.

Run from repo root:  python tools/build_dist.py
(Regenerate datajs first if data/ changed:  python tools/build_data.py)
"""
import os, re, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def read(p):
    with open(os.path.join(ROOT, p), encoding="utf-8") as f:
        return f.read()

def js_safe(s):
    # keep inline scripts valid: never let a literal "</script" terminate the tag
    return s.replace("</script", "<\\/script")

def main():
    html = read("index.html")

    # Stamp the build BEFORE anything is inlined.
    #
    # This has to happen first, and only once. js/report.js builds a print-ready HTML
    # document inside a template string, and that string contains its own "</title>".
    # Stamping after inlining meant str.replace() hit that occurrence too and injected
    # a literal "</script>" into the middle of report.js's inline <script> block, which
    # terminated the tag early: the browser reported "Unexpected end of input" and
    # SBMM.report was simply never defined in the dist -- while the folder build, where
    # report.js is its own file, worked perfectly. Doing it here, against the raw
    # index.html where "</title>" appears exactly once, removes the hazard entirely.
    stamp = datetime.date.today().isoformat()
    html = html.replace(
        "</title>",
        f"</title>\n<!-- single-file build {stamp} — generated by tools/build_dist.py -->"
        "\n<script>window.SBMM_SINGLE_FILE=true;</script>",
        1)

    # inline stylesheets
    def css_repl(m):
        href = m.group(1)
        css = read(href)
        if "leaflet" in href:  # drop image refs that don't exist inside a single file
            css = re.sub(r"url\(images/[^)]+\)", "none", css)
        return "<style>\n" + css + "\n</style>"
    html = re.sub(r'<link rel="stylesheet" href="([^"]+)">', css_repl, html)

    # inline scripts
    def js_repl(m):
        src = m.group(1)
        return "<script>\n" + js_safe(read(src)) + "\n</script>"
    html = re.sub(r'<script src="([^"]+)"></script>', js_repl, html)

    out = os.path.join(ROOT, "dist", "SBMM_Site_Explorer.html")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"dist/SBMM_Site_Explorer.html  {os.path.getsize(out)/1e6:.1f} MB")

if __name__ == "__main__":
    main()
