"""Bake the app's two typefaces into css/fonts.css as base64 @font-face rules.

v26 (docs/V26_UI_AUDIT.md §9): one sans for words, one mono for numbers.

    Inter          (variable, 100-900)  vendor/fonts/Inter-latin-var.woff2
    JetBrains Mono (variable, 100-800)  vendor/fonts/JetBrainsMono-latin-var.woff2

Both are the Latin subset of the Fontsource variable builds, both under the SIL
Open Font License 1.1 (the licence texts sit beside them in vendor/fonts/).

Why base64 and not a url(): nothing may be fetched over file://, and the two
single-file builds inline css/*.css verbatim (tools/build_dist.py), so a data:
URL is the one form that works in all three builds. The fonts are ~88 kB, ~118 kB
as base64 — the cost of the whole change.

Glyphs outside the Latin subset (arrows, box drawing, the ▾ ▼ ✕ the chrome uses)
fall through to the next family in --sans / --mono, which is what unicode-range
is for.

    python tools/build_fonts.py
"""
import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RANGE = ("U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,"
         "U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,"
         "U+2212,U+2215,U+FEFF,U+FFFD")
FACES = [
    ("SBMM Inter", "Inter-latin-var.woff2", "100 900"),
    ("SBMM Mono", "JetBrainsMono-latin-var.woff2", "100 800"),
]


def main():
    out = ["/* GENERATED by tools/build_fonts.py — do not edit by hand.",
           "   Inter and JetBrains Mono (SIL OFL 1.1, vendor/fonts/), Latin subset,",
           "   variable weight, as data: URLs so they load over file:// and inline",
           "   into both single-file builds. */"]
    for fam, fn, wt in FACES:
        with open(os.path.join(ROOT, "vendor", "fonts", fn), "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        out.append("@font-face{font-family:\"%s\";font-style:normal;font-display:swap;"
                   "font-weight:%s;unicode-range:%s;"
                   "src:url(data:font/woff2;base64,%s) format(\"woff2\")}" % (fam, wt, RANGE, b64))
    path = os.path.join(ROOT, "css", "fonts.css")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", path, os.path.getsize(path), "bytes")


if __name__ == "__main__":
    main()
