#!/usr/bin/env python3
"""
Build the single-file distributions from the same source as the folder build.

    python tools/build_dist.py           -> dist/SBMM_Site_Explorer.html        (full)
    python tools/build_dist.py --field   -> dist/SBMM_Site_Explorer_field.html  (field)

Both are one self-contained file (CSS, JS, vendor libs and every data payload
inlined); double-click works anywhere, no folder needed.

THREE BUILDS, ONE SOURCE (docs/V11_SPEC.md 4.2)
-----------------------------------------------
The FIELD build is the full app with four payloads left out, so it opens on a
phone over a cable or a download rather than needing 130 MB of parse:

    i_sheet_full_*.js   the 20 full-sheet plan renders   (~27 MB)
    i_chm_png.js/d_chm  the canopy height model          (~7 MB)
    d_cad_surfaces.js   EA's recovered design surfaces   (~11 MB)
    d_cad_native.js     EA's native CAD                  (~22 MB)

Everything else stays: the three DEMs, all imagery, the design-sheet overlays,
the native design GIS, the datasets, the survey and the (still gated) cultural
payload. The sheet MANIFEST (d_sheets_full.js) stays too — the Sheets tab lists
every drawing and says which ones have no render here.

Every module that reads one of those four must tolerate its absence with a note
or a toast and never an error; test/e2e_field.mjs is the proof.

THE TERRAIN TILES ARE NOT INLINED, AND THAT IS DELIBERATE (v20 section 2)
------------------------------------------------------------------------
index.html carries `datajs/tiles/index.js` and nothing else from the pyramid,
so that 30 kB index is all either dist inlines. The 2,311 tile payloads are
injected on demand by js/tiles.js in the FOLDER build, and in a dist there is
no datajs/ beside the file to inject from -- so js/tiles.js SYNTHESISES a tile
out of the whole rasters this file already inlines. For a DEM tile that is
bit-identical to the payload (the same grid nodes through the same terrain-RGB
step); for imagery it is the same box filter tools/build_tiles.py runs.

Measured, inlining the pyramid takes the full dist from 133 MB to about 206 MB
for information it already carries, which is why nothing here globs
datajs/tiles/. Do not add it. test/terrain3d.mjs runs against the dist and is
what proves the synthesis path draws the same terrain.

The build stamps window.SBMM_BUILD, which js/util.js copies to SBMM_DATA.build,
so the app can say which of the three it is.

Run from the repo root. (Regenerate datajs first if data/ changed:
python tools/build_data.py)
"""
import os, re, sys, datetime, fnmatch

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Payload scripts the field build leaves out. Globs matched against the src
# attribute exactly as index.html writes it.
FIELD_EXCLUDE = [
    "datajs/i_sheet_full_*.js",
    "datajs/i_chm_png.js",
    "datajs/d_chm.js",
    "datajs/d_cad_surfaces.js",
    "datajs/d_cad_native.js",
]

def read(p):
    with open(os.path.join(ROOT, p), encoding="utf-8") as f:
        return f.read()

def js_safe(s):
    # keep inline scripts valid: never let a literal "</script" terminate the tag
    return s.replace("</script", "<\\/script")

def excluded(src, field):
    return field and any(fnmatch.fnmatch(src, pat) for pat in FIELD_EXCLUDE)

def build(field=False):
    html = read("index.html")

    # Stamp the build BEFORE anything is inlined.
    #
    # This has to happen first, and only once. js/report.js builds a print-ready HTML
    # document inside a template string, and that string contains its own "</title>".
    # Stamping after inlining meant str.replace() hit that occurrence too and injected
    # a literal "</script>" into the middle of report.js's inline <script> block, which
    # terminated the tag early: the browser reported "Unexpected end of input" and
    # SBMM.report was simply never defined in the dist -- while the folder build, where
    # report.js is its own file, worked perfectly. Doing it here, against the raw
    # index.html where "</title>" appears exactly once, removes the hazard entirely.
    stamp = datetime.date.today().isoformat()
    kind = "field" if field else "full"
    html = html.replace(
        "</title>",
        f"</title>\n<!-- single-file {kind} build {stamp} — generated by tools/build_dist.py -->"
        "\n<script>window.SBMM_SINGLE_FILE=true;</script>",
        1)
    # the one line index.html carries for this; the folder build reads "full"
    html = html.replace('window.SBMM_BUILD="full"', f'window.SBMM_BUILD="{kind}"', 1)

    # v17 §2: drop the manifest and the icon links.
    #
    # A single-file build is ONE html file that gets emailed and double-clicked;
    # `manifest.webmanifest` and `icons/*.png` are siblings that will not be
    # there, so every one of those links is a guaranteed 404 (and over file://
    # a console error the user sees in the report). The apple/theme META tags
    # stay — they carry no URL, they cost nothing, and a dist opened from a web
    # server still gets the dark status bar from them.
    html = re.sub(r'\n?\s*<link rel="manifest"[^>]*>', "", html)
    html = re.sub(r'\n?\s*<link rel="apple-touch-icon"[^>]*>', "", html)
    html = re.sub(r'\n?\s*<link rel="icon"[^>]*>', "", html)

    # inline stylesheets
    def css_repl(m):
        href = m.group(1)
        css = read(href)
        if "leaflet" in href:  # drop image refs that don't exist inside a single file
            css = re.sub(r"url\(images/[^)]+\)", "none", css)
        return "<style>\n" + css + "\n</style>"
    html = re.sub(r'<link rel="stylesheet" href="([^"]+)">', css_repl, html)

    # inline scripts (skipping the field build's exclusion list)
    dropped = []
    def js_repl(m):
        src = m.group(1)
        if excluded(src, field):
            dropped.append(src)
            return f"<!-- {src} — not in the field build -->"
        return "<script>\n" + js_safe(read(src)) + "\n</script>"
    html = re.sub(r'<script src="([^"]+)"></script>', js_repl, html)

    # v19.1 — the heavy payloads.
    #
    # index.html does not carry them as <script src> tags any more: a phone must
    # not parse ~50 MB of base64 it will never use, so they live in ONE array
    # between the SBMM_HEAVY markers and the page's own loader document.writes
    # them when the profile is not a phone. A single-file build has no loader to
    # run (window.SBMM_SINGLE_FILE short-circuits it), so the whole block is
    # replaced here by the payloads themselves -- inlined verbatim, in list
    # order, honouring FIELD_EXCLUDE exactly as the static tags do.
    m = re.search(r'<script>\n/\* SBMM_HEAVY_BEGIN \*/(.*?)</script>', html, re.S)
    if not m:
        raise SystemExit("build_dist: the SBMM_HEAVY block is gone from index.html")
    heavy = re.findall(r'"([^"]+)"', re.search(r'\[(.*?)\]', m.group(1), re.S).group(1))
    if not heavy:
        raise SystemExit("build_dist: the SBMM_HEAVY list is empty")
    parts = []
    for src in heavy:
        if excluded(src, field):
            dropped.append(src)
            parts.append(f"<!-- {src} - not in the field build -->")
        else:
            parts.append("<script>\n" + js_safe(read(src)) + "\n</script>")
    html = html[:m.start()] + "\n".join(parts) + html[m.end():]

    name = "SBMM_Site_Explorer_field.html" if field else "SBMM_Site_Explorer.html"
    out = os.path.join(ROOT, "dist", name)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(html)
    mb = os.path.getsize(out) / 1e6
    print(f"dist/{name}  {mb:.1f} MB")
    if dropped:
        print(f"  left out {len(dropped)} payload script(s): "
              + ", ".join(sorted(set(os.path.basename(d) for d in dropped))[:6])
              + (" …" if len(set(dropped)) > 6 else ""))
    return out

def main():
    field = "--field" in sys.argv[1:]
    build(field=field)

if __name__ == "__main__":
    main()
